# Generated by Django 5.1.2 on 2025-01-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_diaries', '0006_remove_entry_text_remove_topic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.CharField(default='empty', max_length=200),
            preserve_default=False,
        ),
    ]
