# Generated by Django 5.1.2 on 2025-01-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi_diaries', '0007_entry_text_topic_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='text',
        ),
    ]
