# Generated by Django 5.1.2 on 2025-01-30 12:05

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_diaries', '0008_remove_entry_text_remove_topic_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='digi_diaries.topic')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='sub_topic',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='digi_diaries.subtopic'),
            preserve_default=False,
        ),
    ]
