# Generated by Django 5.1.2 on 2025-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digi_diaries', '0010_entry_title_subtopic_title_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
